<a href="https://colab.research.google.com/github/geovannathereza/curso-de-machine-learning/blob/main/Atividade_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##Obtendo os dados: 
Ao rodarmos a célula abaixo vamos obter os dados diretamente do site:

http://dados.recife.pe.gov.br/tl/dataset/relacao-de-pessoas-vacinadas-covid-19/resource/966e9c4c-df45-40d7-9c58-2f13c61a6d28

In [2]:
df1 = pd.read_csv('http://dados.recife.pe.gov.br/dataset/2b5ee58d-9535-4d80-ab32-f63fd475346e/resource/93f4e8c2-430f-4142-86b3-96dab4905b4e/download/casosgravescovid.csv', sep=";")

Utilize os comandos aprendidos em aula para os dados carregados, começando, preferencialmente, por:
- head()
- head(1-2)
- tail()
- info()
- describe()
- seguindo com outros aprendidos para manipulação de tratamento dos dados.

In [3]:
df1.shape

(36435, 18)

In [4]:
df1.head()

,data_notificacao,sexo,raca,etnia,idade,municipio_residencia,bairro,distrito_sanitario,data_inicio_sintomas,sintomas,outros_sintomas,doencas_preexistentes,outras_doencas_preexistentes,profissional_saude,categoria_profissional,classificacao_final,evolucao,data_obito
0,2020-05-30,Masculino,Branca,NaN,53,Recife,SAN MARTIN,V,2020-05-25,"Febre, Tosse, Mialgia, Alteração/perda de olfa...",NaN,NaN,NaN,NaN,NaN,DESCARTADO,ISOLAMENTO DOMICILIAR,NaN
1,2020-06-02,Feminino,Parda,NaN,0,Recife,ALTO SANTA TEREZINHA,II,2020-05-30,"Febre, Tosse, Dispneia, Saturação O2 < 95",NaN,NaN,NaN,NaN,NaN,INCONCLUSIVO,ISOLAMENTO DOMICILIAR,NaN
2,2020-06-02,Feminino,Parda,NaN,86,Recife,ESPINHEIRO,III,2020-06-01,"Dispneia, Saturação O2 < 95",NaN,NaN,NaN,NaN,NaN,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO,NaN
3,2020-06-01,Masculino,Branca,NaN,66,Recife,CASA FORTE,III,2020-05-25,NaN,NaN,NaN,NaN,NaN,NaN,CONFIRMADO,RECUPERADO,NaN
4,2020-06-02,Masculino,Preta,NaN,68,Recife,ILHA DO RETIRO,IV,2020-05-30,"Tosse, Dispneia, Saturação O2 < 95",NaN,NaN,NaN,NaN,NaN,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO,NaN

In [5]:
df1.tail()

,data_notificacao,sexo,raca,etnia,idade,municipio_residencia,bairro,distrito_sanitario,data_inicio_sintomas,sintomas,outros_sintomas,doencas_preexistentes,outras_doencas_preexistentes,profissional_saude,categoria_profissional,classificacao_final,evolucao,data_obito
36430,2022-06-08,Masculino,Ignorado,NaN,77,Recife,BREJO DA GUABIRABA,VII,2022-06-06,Dispneia,NaN,NaN,HAS,NÃO,NaN,EM ANÁLISE,INTERNADO UTI,NaN
36431,2022-06-09,Masculino,Parda,NaN,74,Recife,NOVA DESCOBERTA,VII,2022-06-06,"Tosse, Cansaço/fadiga, Desconforto respiratóri...",NaN,NaN,NaN,NÃO,NaN,EM ANÁLISE,INTERNADO LEITO DE ISOLAMENTO,NaN
36432,2022-06-10,Masculino,Parda,NaN,74,Recife,BEBERIBE,II,2022-06-03,"Febre, Tosse, Dispneia",NaN,Diabetes,NaN,NÃO,NaN,EM ANÁLISE,INTERNADO LEITO DE ISOLAMENTO,NaN
36433,2022-06-12,Feminino,Amarela,NaN,73,Recife,ENGENHO DO MEIO,IV,2022-06-11,"Dispneia, Desconforto respiratório / aperto to...",NaN,"Doenças Cardíacas ou Vasculares, Diabetes",AVC,NÃO,NaN,EM ANÁLISE,INTERNADO UTI,NaN
36434,2022-06-12,Feminino,Parda,NaN,66,Recife,BOA VIAGEM,VI,2022-06-07,"Tosse, Dispneia, Desconforto respiratório / ap...",RNC,NaN,AVCH,NÃO,NaN,EM ANÁLISE,INTERNADO UTI,NaN

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36435 entries, 0 to 36434
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   data_notificacao               36435 non-null  object
 1   sexo                           36435 non-null  object
 2   raca                           30106 non-null  object
 3   etnia                          4 non-null      object
 4   idade                          36435 non-null  object
 5   municipio_residencia           36435 non-null  object
 6   bairro                         36435 non-null  object
 7   distrito_sanitario             36435 non-null  object
 8   data_inicio_sintomas           36435 non-null  object
 9   sintomas                       34477 non-null  object
 10  outros_sintomas                5974 non-null   object
 11  doencas_preexistentes          13698 non-null  object
 12  outras_doencas_preexistentes   7807 non-null   object
 13  profissional_saude             27338 non-null  object
 14  categoria_profissional         2914 non-null   object
 15  classificacao_final            36435 non-null  object
 16  evolucao                       35458 non-null  object
 17  data_obito                     9344 non-null   object
dtypes: object(18)
memory usage: 5.0+ MB

In [7]:
df1.describe()

,data_notificacao,sexo,raca,etnia,idade,municipio_residencia,bairro,distrito_sanitario,data_inicio_sintomas,sintomas,outros_sintomas,doencas_preexistentes,outras_doencas_preexistentes,profissional_saude,categoria_profissional,classificacao_final,evolucao,data_obito
count,36435,36435,30106,4,36435,36435,36435,36435,36435,34477,5974,13698,7807,27338,2914,36435,35458,9344
unique,836,3,6,1,127,3,106,10,850,3440,2370,244,3344,2,23,4,5,785
top,2020-04-23,Feminino,Parda,Ignorado,57,Recife,BOA VIAGEM,IV,2020-04-20,"Febre, Tosse, Dispneia, Saturação O2 < 95",ASTENIA,Doenças Cardíacas ou Vasculares,HAS,NÃO,Outro profissional de serviço de saúde,CONFIRMADO,RECUPERADO,2020-05-09
freq,464,18643,15040,4,646,36433,2972,6392,359,2535,946,3827,1493,24424,1900,17816,18931,72

In [8]:
df1.isnull()

,data_notificacao,sexo,raca,etnia,idade,municipio_residencia,bairro,distrito_sanitario,data_inicio_sintomas,sintomas,outros_sintomas,doencas_preexistentes,outras_doencas_preexistentes,profissional_saude,categoria_profissional,classificacao_final,evolucao,data_obito
0,False,False,False,True,False,False,False,False,False,False,True,True,True,True,True,False,False,True
1,False,False,False,True,False,False,False,False,False,False,True,True,True,True,True,False,False,True
2,False,False,False,True,False,False,False,False,False,False,True,True,True,True,True,False,False,True
3,False,False,False,True,False,False,False,False,False,True,True,True,True,True,True,False,False,True
4,False,False,False,True,False,False,False,False,False,False,True,True,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36430,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,False,True
36431,False,False,False,True,False,False,False,False,False,False,True,True,True,False,True,False,False,True
36432,False,False,False,True,False,False,False,False,False,False,True,False,True,False,True,False,False,True
36433,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,True
36434,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True

In [9]:
df2 = df1.drop(columns= ['etnia', 'data_notificacao', 'idade', 'sexo', 'data_inicio_sintomas', 'profissional_saude', 'categoria_profissional'])
df2

,raca,municipio_residencia,bairro,distrito_sanitario,sintomas,outros_sintomas,doencas_preexistentes,outras_doencas_preexistentes,classificacao_final,evolucao,data_obito
0,Branca,Recife,SAN MARTIN,V,"Febre, Tosse, Mialgia, Alteração/perda de olfa...",NaN,NaN,NaN,DESCARTADO,ISOLAMENTO DOMICILIAR,NaN
1,Parda,Recife,ALTO SANTA TEREZINHA,II,"Febre, Tosse, Dispneia, Saturação O2 < 95",NaN,NaN,NaN,INCONCLUSIVO,ISOLAMENTO DOMICILIAR,NaN
2,Parda,Recife,ESPINHEIRO,III,"Dispneia, Saturação O2 < 95",NaN,NaN,NaN,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO,NaN
3,Branca,Recife,CASA FORTE,III,NaN,NaN,NaN,NaN,CONFIRMADO,RECUPERADO,NaN
4,Preta,Recife,ILHA DO RETIRO,IV,"Tosse, Dispneia, Saturação O2 < 95",NaN,NaN,NaN,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO,NaN
...,...,...,...,...,...,...,...,...,...,...,...
36430,Ignorado,Recife,BREJO DA GUABIRABA,VII,Dispneia,NaN,NaN,HAS,EM ANÁLISE,INTERNADO UTI,NaN
36431,Parda,Recife,NOVA DESCOBERTA,VII,"Tosse, Cansaço/fadiga, Desconforto respiratóri...",NaN,NaN,NaN,EM ANÁLISE,INTERNADO LEITO DE ISOLAMENTO,NaN
36432,Parda,Recife,BEBERIBE,II,"Febre, Tosse, Dispneia",NaN,Diabetes,NaN,EM ANÁLISE,INTERNADO LEITO DE ISOLAMENTO,NaN
36433,Amarela,Recife,ENGENHO DO MEIO,IV,"Dispneia, Desconforto respiratório / aperto to...",NaN,"Doenças Cardíacas ou Vasculares, Diabetes",AVC,EM ANÁLISE,INTERNADO UTI,NaN
36434,Parda,Recife,BOA VIAGEM,VI,"Tosse, Dispneia, Desconforto respiratório / ap...",RNC,NaN,AVCH,EM ANÁLISE,INTERNADO UTI,NaN

In [10]:
df2.isnull().sum()

raca                              6329
municipio_residencia                 0
bairro                               0
distrito_sanitario                   0
sintomas                          1958
outros_sintomas                  30461
doencas_preexistentes            22737
outras_doencas_preexistentes     28628
classificacao_final                  0
evolucao                           977
data_obito                       27091
dtype: int64

In [29]:
df3 = df2.drop(columns=['outros_sintomas', 'raca', 'doencas_preexistentes', 'data_obito'])
df3

,municipio_residencia,bairro,distrito_sanitario,sintomas,outras_doencas_preexistentes,classificacao_final,evolucao
0,Recife,SAN MARTIN,V,"Febre, Tosse, Mialgia, Alteração/perda de olfa...",NaN,DESCARTADO,ISOLAMENTO DOMICILIAR
1,Recife,ALTO SANTA TEREZINHA,II,"Febre, Tosse, Dispneia, Saturação O2 < 95",NaN,INCONCLUSIVO,ISOLAMENTO DOMICILIAR
2,Recife,ESPINHEIRO,III,"Dispneia, Saturação O2 < 95",NaN,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO
3,Recife,CASA FORTE,III,NaN,NaN,CONFIRMADO,RECUPERADO
4,Recife,ILHA DO RETIRO,IV,"Tosse, Dispneia, Saturação O2 < 95",NaN,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO
...,...,...,...,...,...,...,...
36430,Recife,BREJO DA GUABIRABA,VII,Dispneia,HAS,EM ANÁLISE,INTERNADO UTI
36431,Recife,NOVA DESCOBERTA,VII,"Tosse, Cansaço/fadiga, Desconforto respiratóri...",NaN,EM ANÁLISE,INTERNADO LEITO DE ISOLAMENTO
36432,Recife,BEBERIBE,II,"Febre, Tosse, Dispneia",NaN,EM ANÁLISE,INTERNADO LEITO DE ISOLAMENTO
36433,Recife,ENGENHO DO MEIO,IV,"Dispneia, Desconforto respiratório / aperto to...",AVC,EM ANÁLISE,INTERNADO UTI
36434,Recife,BOA VIAGEM,VI,"Tosse, Dispneia, Desconforto respiratório / ap...",AVCH,EM ANÁLISE,INTERNADO UTI

In [12]:
df3.distrito_sanitario.unique()

array(['V', 'II', 'III', 'IV', 'VII', 'I', 'VIII', 'VI', 'IGN', 'v'],
      dtype=object)

In [19]:
df3.evolucao.unique()

array(['ISOLAMENTO DOMICILIAR', 'INTERNADO LEITO DE ISOLAMENTO',
       'RECUPERADO', 'ÓBITO', nan, 'INTERNADO UTI'], dtype=object)

In [31]:
df4 = df3.dropna()
df4

,municipio_residencia,bairro,distrito_sanitario,sintomas,outras_doencas_preexistentes,classificacao_final,evolucao
13,Recife,LINHA DO TIRO,II,"Febre, Tosse, Dispneia",DOENCA NEUROLOGICA,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO
74,Recife,BOA VISTA,I,Saturação O2 < 95,NEOPLASIAS,CONFIRMADO,RECUPERADO
130,Recife,TEJIPIO,V,"Tosse, Dispneia, Desconforto respiratório / ap...",ALZHEIMER,DESCARTADO,ÓBITO
147,Recife,VARZEA,IV,"Febre, Tosse",HAS E AVC?,CONFIRMADO,RECUPERADO
184,Recife,SAN MARTIN,V,"Dispneia, Desconforto respiratório / aperto to...",ETILISTA,DESCARTADO,ÓBITO
...,...,...,...,...,...,...,...
36418,Recife,TORRE,IV,"Tosse, Dispneia, Dor de Garganta",B24,DESCARTADO,INTERNADO LEITO DE ISOLAMENTO
36425,Recife,AGUA FRIA,II,"Vômito, Diarreia",tabagista,EM ANÁLISE,ÓBITO
36430,Recife,BREJO DA GUABIRABA,VII,Dispneia,HAS,EM ANÁLISE,INTERNADO UTI
36433,Recife,ENGENHO DO MEIO,IV,"Dispneia, Desconforto respiratório / aperto to...",AVC,EM ANÁLISE,INTERNADO UTI
36434,Recife,BOA VIAGEM,VI,"Tosse, Dispneia, Desconforto respiratório / ap...",AVCH,EM ANÁLISE,INTERNADO UTI

In [65]:
df3.evolucao

0                ISOLAMENTO DOMICILIAR
1                ISOLAMENTO DOMICILIAR
2        INTERNADO LEITO DE ISOLAMENTO
3                           RECUPERADO
4        INTERNADO LEITO DE ISOLAMENTO
                     ...
36430                    INTERNADO UTI
36431    INTERNADO LEITO DE ISOLAMENTO
36432    INTERNADO LEITO DE ISOLAMENTO
36433                    INTERNADO UTI
36434                    INTERNADO UTI
Name: evolucao, Length: 36435, dtype: object

In [66]:
df3.distrito_sanitario

0          V
1         II
2        III
3        III
4         IV
        ...
36430    VII
36431    VII
36432     II
36433     IV
36434     VI
Name: distrito_sanitario, Length: 36435, dtype: object